#CRIE UM PACOTE CHAMADO UTILIDADESCEV QUE TENHA DOIS MÓDULOS INTERNOS CHAMADOS MOEDA E DADO. TRANSFIRA TODAS AS FUNÇÕES
#UTILIZADAS NOS DESAFIOS MOEDA2, MOEDAS3, MOEDAS4 E MOEDAS5 PARA O PRIMEIRO PACOTE E MANTENHA TUDO FUNCIONANDO.

from moeda5.utilidadescv import moeda
from moeda5.utilidadescv import dado
p = float(input('Digite o preço:R$ '))

moeda.resumo(p, 20, 12)


