#MODIFIQUE AS FUNÇÕES QUE FORAM CRIADAS NO DESAFIO MOEDAS2 PARA QUE ELAS ACEITEM UM PARÂMETRO A MAIS, INFORMANDO SE O
# VALOR RETORNADO POR ELAS VAI SER OU NÃO FORMATADO PELA FUNÇÃO MOEDA(), DESENVOLVIDA NO DESAFIO MOEDA2

import moeda4
p = float(input('Digite o preço: '))

moeda4.resumo(p)


